import { Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'surf-101', name: 'Surf 101' },
  { id: 'surf-foundation', name: 'Surf Foundation' },
  { id: 'surf-acelerator', name: 'Surf Acelerator' },
  { id: 'surf-camp-kids', name: 'Surf Camp Kids' },
  { id: 'surf-camp-adultos', name: 'Surf Camp Adultos' },
  { id: 'tour-pesca-otoque-bona', name: 'Tour de Pesca Otoque y Bona' },
  { id: 'escapate-isla-otoque', name: 'Escápate a Isla Otoque y Bona' },
  { id: 'day-pass-taborcillo', name: 'Day Pass Taborcillo' },
  { id: 'manglares-taborcillo', name: 'Manglares + Taborcillo' },
  { id: 'avistamiento-ballenas', name: 'Avistamiento de Ballenas' },
  { id: 'kite-surf', name: 'Kite Surf' },
  { id: 'kite-surf-pack', name: 'Kite Surf Pack' },
  { id: 'wing-foil', name: 'Wing Foil' },
  { id: 'jet-ski', name: 'Jet Ski' },
  { id: 'tubing-inflable', name: 'Tubing Inflable' },
  { id: 'mulita', name: 'Mulita' },
  { id: 'scooter', name: 'Scooter' },
  { id: 'caracol-sunset-cruise', name: 'Caracol Sunset Cruise' },
  { id: 'sail-away-party', name: 'Sail Away Party' },
  { id: 'day-pass-bona-otoque', name: 'Day Pass Bona y Otoque' },
  { id: 'fun-fishing', name: 'Fun Fishing' },
  { id: 'pro-fishing', name: 'Pro Fishing' },
  { id: 'hiking-cerro-chame', name: 'Hiking Cerro Chame' },
  { id: 'day-pass-laguna', name: 'Day Pass Laguna San Carlos' },
  { id: 'tour-cascada-filipinas', name: 'Tour Cascada Filipinas' },
  { id: 'tour-cascadas-manglarito', name: 'Tour Cascadas Manglarito' },
  { id: 'tour-cascada-la-gloria', name: 'Tour Cascada La Gloria' },
  { id: 'tour-7-cascadas', name: 'Tour 7 Cascadas' },
  { id: 'rappel-cascada', name: 'Rappel Cascada Filipinas' },
  { id: 'cascada-manantial', name: 'Cascada Manantial de Vida' },
  { id: 'day-trip-el-valle', name: 'Day Trip El Valle de Antón' },
  { id: 'rafting-tubing', name: 'Rafting Tubing Cajones' },
  { id: 'mountain-bike', name: 'Mountain Bike' },
  { id: 'sky-dive', name: 'Sky Dive' },
  { id: 'canopy-chame', name: 'Canopy Chame' },
  { id: 'wave-surf', name: 'Wave Surf' },
];
